### ISSUE TITLE
The app using this library won't be uploaded on Google Play

### ISSUE THREAD

**Issue by talhaqamar** [SignalR/java-client#76]
Hi,
I am using this library for a chat app in android.
I firstly developed eclipse based project and use the jar files.The app is working fine.

But when i try to upload the app to the Google Play.It shows me a message that your app doesn't supports any devices.
I even tried to upload the app without the libraries then it gets uploaded supports over 6K android devices.

As this library is updated for gradle for android.So i simply convert it into gradle project for android studio as well.Works perfectly but still won't supports any devices.(Below image is the output for eclipse and gradle project as well..No supported devices )
![knxoa](https://cloud.githubusercontent.com/assets/2019864/7136443/70103782-e2ca-11e4-9a1f-10dbadacc9cb.png)

Any body who helps me.Thanks in advance.

Regards,
Talha

**Comment by sattha** [comment]
I also use the jar files but I have not experienced this problem before.

**Comment by ssawchenko** [comment]
We are seeing the exact same issue. Using the jar files gives us the "0 supported devices" issue. Removing the libraries from our application results in 6k+ device support.

I have spent all day trying to figure out how to generate and use the aar/jar combination (since now the project results in those files instead of 2 jars), however, I am stuck with https://github.com/SignalR/java-client/issues/62 and cannot actually get my application to function correctly because of it.

Any help would be appreciated as we are essentially now a day behind on launching.

**Comment by talhaqamar** [comment]
I had solved the issue and i posted this on the stackoverflow as well.
You can check the full solution here :
https://stackoverflow.com/questions/29565203/supported-devices-0-on-google-play/29770789#29770789

Use Solution 2 mentioned in the above link.
