### ISSUE TITLE
Java JDK 1.7 Required

### ISSUE THREAD

**Issue by vpatel-fintech** [SignalR/java-client#87]
I have installed JDK 1.8 and try to build project and faced some issue than I tried with 1.7 JDK and works fine.

**Comment by sonaysevik** [comment]
Same problem is available for me too.

**Comment by sattha** [comment]
Please see my question at...

https://stackoverflow.com/questions/33196087/gradle-compile-success-but-fail-to-run-project

**Comment by sattha** [comment]
You can exclude other project

include ':signalr-client-sdk', ':signalr-client-sdk-android'
//        ':signalr-client-tests', ':signalr-client-test-integration-base',
//        ':signalr-client-test-integration-java', ':signalr-client-test-integration-android'

 and remove v7 from
signalr-client-android-sdk module since it never used

aferthat, try to build with jdk you want

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
